### ISSUE TITLE
Scale Volume Control

### ISSUE THREAD

**Issue by jtmaverick** [mavericksoftwareconsulting/mavboard#2]
Our volume control sucks - 3 is too quiet, 4 is too loud and 5+ is crazy.

Would like someone to look into these mixer settings and see if we can map a volume scale to mopidy.

IE, Volume levels 1-8 would map to 1-100 - giving us a lot more control over volume.

https://github.com/mopidy/mopidy-alsamixer/issues/3

**Comment by nathanbrophy** [comment]
Looks like an extension to mopidy was added we can install from the github.  Will need to replace some of our current files in the mopidy source library with the audio mixer files from the other github.  Adds optionality to set a volume scaling and min/max volume setting.  Also allows us to use a logarithmic scale instead of a linear one.  This should help a lot.  We can also look into using it as a mapping from quieter volumes and use a logarithmic scale, if it is still too loud.
