### ISSUE TITLE
Build errors out 

### ISSUE THREAD

**Issue by nathanbrophy** [mavericksoftwareconsulting/mavboard#9]
Found in package.json, under scripts section. 

Original: "npm run compile; node ./bin/www"

New/Suggested: "npm run compile & node ./bin/www"

With the original, when running on windows would get the error that we are missing script compile.  Changing it to the & sign instead in the new/suggested one, allows it to run just fine and compiles and builds the project.  Not really sure why this is an issue, or if it's just a me issue.  Try compiling both ways and see what happens.  npm run compile works by itself no matter what version you use as well.

**Comment by thornjad** [comment]
I originally wrote that line, and I've since learned better, and it's actually an npm issue. The problem is that `npm run compile` is supposed to be an invalid command, even though it sometimes works. The proper way to use the compile script is `npm run-script compile`.

Also, using `&&` to chain commands is better, because it will only run the right-hand command if the left-side succeeds.

So I think the new line should be `npm run-script compile && node ./bin/www`

**Comment by thornjad** [comment]
Correction, `npm run` is the same as `npm run-script`, so `npm run compile`.
